language: python

sudo: required

python:
  - "3.4"
  - "3.5"
  - "3.6"
    
env:
  - TEST="flake8"

before_install:
  # install flake8 to perform python code style check in the script part
  # install it using pip in order to get the newest version
  - if [ $TEST == "flake8" ]; then sudo apt-get update -qq ; fi
  - if [ $TEST == "flake8" ]; then sudo apt-get install -qq python-pip; fi
  - if [ $TEST == "flake8" ]; then sudo pip install flake8; fi

install:
  - pip install -r requirements.txt

script:
  - flake8 .
  - pytest .