language: python

sudo: required

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  # install flake8 to perform python code style check in the script part
  # install it using pip in order to get the newest version
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-pip

install:
  - pip install flake8, pytest
  - pip install udkm1Dsimpy

script:
  - flake8 .
  - pytest .